### ISSUE TITLE
Would it be possible to support Handlebar/Mustache templates?

### ISSUE THREAD

**Issue by voxpelli** [htmllint/htmllint#101]
I would like to get some rudimentary Handlebars-linting in place.

Currently I'm stuck with it complaining about the following class name not following the naming practice.

```html
<body class="{{#if errorMsg}}error {{/if}}{{#if success}}success {{/if}}">
```

I'm wondering whether one could simply remove all `{{...}}` to maybe make Handlebar/Mustache templates more lintable out of the box, and if that's not something you want to provide out of the box then maybe a preprocess-method that could either render the Handlebar template or just remove the Handlebar-tags could be a solution? Such an option could perhaps be added directly to this or to eg. `grunt-htmllint`?

**Comment by mbarlock** [comment]
With all the templating languages out there I wouldn't imagine supporting one would be a great idea. I generate my handlebars and then run the generated files through htmllint. Obviously that isn't always possible. Also every templating language has its own quirks. Probably wouldn't be the worst thing to have a handlesbars linter

**Comment by mlochbaum** [comment]
Fixed with `id-class-ignore-regex` (see also issue #110).
