### ISSUE TITLE
attr-name-style: fatal error if tabindex present

### ISSUE THREAD

**Issue by waffledonkey** [htmllint/htmllint#104]
if you have a tabindex attribute present, the linter breaks on:

`Fatal error: op is not defined.`

regardless of what format you choose -- even false.  I'm stuck and have to turn off linting for the time being

**Comment by waffledonkey** [comment]
I'm not sure why it's griefing me, but the issue seems to be messages.js E026 that <%= op %> is not defined.  If you pull him out of the message it works fine.  If you go back to focusable-tabindex-style.js line 26 there appears to be a section where op is commented out and a question unused?

Hope that helps -- I'm good for now with some local hacking

**Comment by mlochbaum** [comment]
Not so unused after all...

I should look into why our tests didn't catch this, but for now I'll just push the fix.
