### ISSUE TITLE
Issue with linting EJS code

### ISSUE THREAD

**Issue by markhaja** [htmllint/htmllint#106]
Have the following line containing EJS:
`<span class="slide-panel-label"> <%= user.userid||user.email %> </span>`
I get the following error:

Running "htmllint:src" (htmllint) task
>> views/includes/customization-menu.html: (E002), line 4, col 42, attribute names must match the format: dash

I needed to turn off the attribute-name-style check to get around this error.

**Comment by mlochbaum** [comment]
We don't support EJS (or any html extension). The code you gave is not valid html, hence the linter error. The easy way around this is to run htmllint on the output rather than the input of your EJS tool.
