### ISSUE TITLE
document tag-name-match in wiki

### ISSUE THREAD

**Issue by pdehaan** [htmllint/htmllint#107]
Re: https://github.com/htmllint/htmllint/wiki/Options

It only seems to be mentioned in the [`tag-name-lowercase`](https://github.com/htmllint/htmllint/wiki/Options#tag-name-lowercase) description, and I missed it initially while going through the docs.

**Comment by mlochbaum** [comment]
That whole page was a bit out of date. Fixed now.

**Comment by pdehaan** [comment]
Awesome, thanks so much for the quick turnaround.
