### ISSUE TITLE
Only treat valid tags as real tags

### ISSUE THREAD

**Issue by donaldpipowitch** [htmllint/htmllint#109]
I have annotations like `<p><%= some.cool.message %></p>` which renders fine as HTML even if I don't process `<%= some.cool.message %>` (which would be exchanged with some text on our build step). But htmllint treats `%=` as an invalid attribute name (`attr-name-style`).

Update: Writing the annotation this way `<%=some.cool.Message %>` throws an `tag names must be lowercase`. (No space between `=` and `some` and some upper case character.)

**Comment by mlochbaum** [comment]
I don't think it's reasonable to make htmllint handle these kinds of tags. Although browsers will ignore them, they are incorrect html as there is no closing tag. It seems easy enough to work around this by replacing `<%=` with `<--` and `%>` with `-->` before feeding your pages to htmllint.

I suppose I would reconsider if a lot of users had special tags of exactly this form, but that seems unlikely.

**Comment by donaldpipowitch** [comment]
Hmm... Maybe there aren't a lot users who use these annotations, but I think it would be nice if htmllint would behave like a browser in a more general sense. If the browser renders these annotations as text and not as HTML tags, it would be nice if htmllint would do the same.

**Comment by romnempire** [comment]
After looking at the spec, I think that what you're describing is
technically not a tag. But it looks very element-like.  I think allowing
pseudo-element text is a bad idea - it makes it hard to determine if what
you're reading is html or not, and linted code should be readable.  I think
htmllint should do something when it encounters these element-like text
strings.

**Comment by mlochbaum** [comment]
The difference between a browser and htmllint is that the browser is designed to show you a page--if it can work through invalid html, it should. On the other hand, the purpose of htmllint is to make sure your page conforms to specifications and style guidelines. It's very reasonable to mark an error even for things the browser handles properly.

**Comment by mlochbaum** [comment]
I think the solutions to #155 pretty much fix this. That is, setting `raw-ignore-regex` to `/\<%=.*?%\>/` will remove tags like the one you gave.

I guess there's room to ignore dom-like elements which match a given regex and make it through the parser, but I don't like relying on not-really-tags being parsed correctly.
