### ISSUE TITLE
Be smart about common templating/interpolation solutions

### ISSUE THREAD

**Issue by donaldpipowitch** [htmllint/htmllint#110]
It would be nice to opt-in for common templating/interpolation sollutions. In our Angular directives we have HTML like that: `<span class="foo-bar baz-{{ var }}>{{ value }}</span>`. This throws an `'id-class-style'` error if used with `'dash'`. It would be nice if I could set `{{` and `}}` as delimiters, so a class containing delimiters will be ignored.

**Comment by mlochbaum** [comment]
I'll make an option to ignore tag names based on a regex. That seems like the cleanest way to support this and similar html extensions.

**Comment by donaldpipowitch** [comment]
Sounds good, thanks!

**Comment by mlochbaum** [comment]
See the new `id-class-ignore-regex` option.
