### ISSUE TITLE
Separate indentation rules for attributes

### ISSUE THREAD

**Issue by donaldpipowitch** [htmllint/htmllint#111]
I would like to indent all tags and text node with 2 spaces, but v-align my attributes. Like this:
````
<p> 
  Some text...
  <span id="foo"
        class="bar">
    Some other text...
  </span>
<p>
````

Currently this would throw an error, because `class` isn't indented with 6 spaces.

**Comment by mlochbaum** [comment]
Just set `indent-width` to false. There really is no way for htmllint to detect which indentations are sensible and which aren't.

**Comment by donaldpipowitch** [comment]
Is this a limitation of `htmlparser2`? Should I request  the feature there?

**Comment by mlochbaum** [comment]
No, just a limitation of reality. htmllint could detect this specific case, but there are many other things you could potentially want to align and no way to determine which of those should be accepted by the linter. Trying to detect this case makes the linting rules more difficult to understand for a very narrow benefit.
