### ISSUE TITLE
Basic tag validation doesn't work

### ISSUE THREAD

**Issue by Kreozot** [htmllint/htmllint#114]
Seems like not closed or closed-but-not-opened tags are totally ok and does not triggering any errors. Why is that?

**Comment by mlochbaum** [comment]
It's a bug (and a rather bad one--perhaps we thought the linter would handle it for us, but that's a poor excuse). I'll make a new rule or two to do this.

**Comment by mlochbaum** [comment]
Fixed to the greatest extent possible given our parser's output. Closed tags with no open tag are dropped by the parser, so they can't be detected during linting.

**Comment by romnempire** [comment]
Is this within the scope of the project?  I thought we generally assumed
the input was valid xml-ish markup before linting, and that this kind of
rule was excluded intentionally and not by oversight.  Without changing the
parser, we can either do validation kinda shittily or not at all.

**Comment by mlochbaum** [comment]
The functional spec (which I am about to remove) lists

> A beginner to html wishes to verify that his or her test webpages are correct and follow good practice.

among the possible use cases, and

> 2. Verification of basic HTML5 compliance (e.g. matched angle brackets and tags).

among our goals (coming before good practice and style issues!). There are a number of validation options already, like `attr-no-dup`. We definitely acknowledged that htmllint is not a validator while writing it, but I don't think that precludes adding sanity checking where we can.

**Comment by sveisvei** [comment]
Did do a simple Markup checker: https://www.npmjs.com/package/unclosed-markup

**Comment by mlochbaum** [comment]
For performance reasons htmllint really needs to only parse the input once. So while it might be a good idea to also run other tools on pages, I can't add a stand-alone tool like this to htmllint.
