### ISSUE TITLE
brackets-htmllint

### ISSUE THREAD

**Issue by ficristo** [htmllint/htmllint#127]
Is this plugin still supported?
I filed this issue https://github.com/htmllint/brackets-htmllint/issues/5 but I don't yet have received a response.

**Comment by ficristo** [comment]
@coalman is there still someone working on htmllint?

**Comment by ficristo** [comment]
@mlochbaum ping?

**Comment by mlochbaum** [comment]
I don't have access to the brackets plugin. I'll see if I can find who does.

**Comment by messman** [comment]
@mlochbaum, I was the owner. Just transferred it to you as I am no longer associated with this project. Feel free to hand it off as you like. To modify/access it, go to the registry site and sign in with your GitHub account, then find it in the list.

**Comment by ficristo** [comment]
@messman Do I have access to the repo too? I'll take a look at extension registry.
Thank you.

**Comment by mlochbaum** [comment]
I have updated the registry now. It looks like there can be only one owner of the registry entry, so I can't give anyone else access. I'll make sure to update the brackets plugin along with htmllint. Send an issue to the brackets-htmllint repository if I forget.
