### ISSUE TITLE
attr-name-style default is not "true"

### ISSUE THREAD

**Issue by radek-holy** [htmllint/htmllint#133]
According to the documentation:
> If no default is specified, the default value is `true`.

However, it's `lowercase` apparently (in version 0.9.12):
> app/body.html: line 5, col 6, attribute names must match the format: lowercase

I know that `true` does not make sense in this case nevertheless the default behaviour does not match the documentation.

**Comment by mlochbaum** [comment]
I have added defaults to the wiki page on options, which fixes this and the previous five issues. Please combine things like this into one issue in the future.

The most reliable source for information about default values is always lib/presets/default.js, as it is the file actually used by htmllint.

**Comment by radek-holy** [comment]
Well, I am sure that the code is the most reliable source of the actual behaviour. But usually the documentation is the most reliable source of the *expected* behaviour. And the expected behaviour is more important to me than the reality. I hope that you don't mean that I should not trust your documentation. Wrong documentation is worse than nothing.

Either way, thank you for the fix.
