### ISSUE TITLE
id-class-style/class-style: someComponent__subComponent isn't possible

### ISSUE THREAD

**Issue by timkraut** [htmllint/htmllint#152]
Hi,

I've got an issue with the available option for `id-class-style`/`class-style`: Using camelCased names combined with underscores (for BEM) isn't possible. I think, the best option would be to allow passing in a regex so that any format can be specified.

**Comment by mlochbaum** [comment]
"bem" is an allowed format specifier--see the top of the options list. I may add a general regex in the future (it's not hard), but that should cover your use case.

**Comment by mlochbaum** [comment]
Actually a regex (an actual RegExp, not a string containing one) is allowed as an option. I've updated the docs to reflect that.

**Comment by timkraut** [comment]
@mlochbaum The issue that I had with the existing BEM Regex is that it doesn't recognize camelCased names. Example:
`some-block__with-modifier--works-fine` No problem here.

`anotherBlock__withModifier_doesntWork` This doesn't work. 

But I've checked the [documentation](https://en.bem.info/methodology/naming-convention/) and actually found that BEM prefers hyphen-separated names. Using a Regex will work for me. Thanks for updating the docs!
