### ISSUE TITLE
Is it posible to change the format specifier for giving values

### ISSUE THREAD

**Issue by Mydeen-SN** [htmllint/htmllint#153]
Hi,
I use htmllint while l use value for id in camelcase (id ="testId") i got error value must match the format: underscore (E011) any way to change the underscore to none.

**Comment by mlochbaum** [comment]
Set `id-class-style` to "camel", or "none" if you really want to remove all checking. See https://github.com/htmllint/htmllint/wiki/Options#id-class-style.
