### ISSUE TITLE
id-style not listed in documentation

### ISSUE THREAD

**Issue by pensierinmusica** [htmllint/htmllint#160]
Hi,

`id-style` doesn't seem to be present in the [options documentation](https://github.com/htmllint/htmllint/wiki/Options).

Can you please check?

Thanks!

**Comment by mlochbaum** [comment]
In fact there is no such option. There are two rules, `id-style.js` and `class-style.js` (currently part of `class.js`) which are controlled by the options `id-class-style` and `class-style`. I realize this is confusing but I'm not sure of a clearer way to document it. I will add a note to the `class-style` option indicating that there is no symmetric `id-style`, however.

The two current options were decided on as part of #122. For the difference between rules and options, see [the wiki](https://github.com/htmllint/htmllint/wiki/Rules-versus-Options).

**Comment by pensierinmusica** [comment]
I see, the problem then is that the error reporter still outputs `id-style`.

Maybe this needs to be changed to `id-class-style` what do you think?

Cheers!

**Comment by mlochbaum** [comment]
The error is returned with a rule, not an option. Adding the option to the output is on my to-do list.
