### ISSUE TITLE
Attribute order

### ISSUE THREAD

**Issue by wayneashleyberry** [htmllint/htmllint#163]
Perhaps this rule already exists, I couldn't find it anywhere... but enforcing a particular attribute order would be great!

**Comment by mlochbaum** [comment]
We definitely don't have such an option currently. I can implement a rule which takes a list option `attribute-order` and enforces that any attributes present in the list are in the given order. Anything more sophisticated, like partial ordering (such as "make sure either of these two attributes are before a third one, but their relative ordering doesn't matter") is too much for htmllint's current option architecture to handle.
