### ISSUE TITLE
Unlisted releases

### ISSUE THREAD

**Issue by tony19** [htmllint/htmllint#168]
npm lists this package at 0.5.0, but your GitHub releases only go up to 0.2.7, and the `HISTORY` file stops at 0.4.0. I'm guessing "v.Next" is 0.5.0.

It would be helpful to have at least one source indicate the latest release and their release dates :)

**Comment by mlochbaum** [comment]
Okay, fixed the history. What is a Github release? Michael handled releases up to 0.2.7 but doesn't work on htmllint now.

**Comment by tony19** [comment]
Click the "releases" link from the GitHub project's home page.
![screen shot 2017-01-13 at 5 22 46 pm](https://cloud.githubusercontent.com/assets/26580/21949074/fbe3360a-d9b4-11e6-81af-504371c7d4b8.png)

The [GitHub docs](https://help.github.com/articles/creating-releases/) explains the procedure. Let me know if you need help with this.

**Comment by mlochbaum** [comment]
Looks like I actually just needed to push my local tags to Github. Do the newer releases work now?

**Comment by tony19** [comment]
Thanks. Yes, they appear in the releases tab now. One last request is to "publish" the release by:

 1. In the releases tab, click **Edit** next to the release tag you'd like to publish.
 2. In the next window, click **Publish Release**.

**Comment by mlochbaum** [comment]
Well, that's a confusing UI. Thanks for your help! I'll leave the older tags (pre-0.3.0) unpublished unless you have a reason that I should publish them.
