### ISSUE TITLE
If attr-name-style is set to lowercase, then an attribute with dashes in it returns an error

### ISSUE THREAD

**Issue by MichaelManhire** [htmllint/htmllint#170]
Given the following configuration, `"attr-name-style": "lowercase"`, and the following HTML, `<meta http-equiv="x-ua-compatible" content="ie=edge">`, htmllint returns this error: `attribute names must match the format: lowercase`.

I understand that it's possible to prevent this with the `attr-name-ignore-regex` option, but it seems like `lowercase` shouldn't be excluding dashes, only uppercase letters.

**Comment by mlochbaum** [comment]
The style "dash" is used to specify lowercase allowing dashes. It would be unreasonable for htmllint to support every possible style variation, so if that option doesn't work for you, you can pass in your own RegExp as well.
