### ISSUE TITLE
X-UA-Compatible problem

### ISSUE THREAD

**Issue by nicothin** [htmllint/htmllint#182]
I use config:
```
{
  "attr-name-ignore-regex": "/X-UA-Compatible/",
  "attr-name-style": "lowercase",
}
```
`<meta http-equiv="X-UA-Compatible" content="ie=edge">` — this tag results in an error :(
what am I doing wrong?
how can I configure it to ignore `http-equiv="X-UA-Compatible"`?

**Comment by regepan** [comment]
@nicothin 
Try it.
```
"attr-name-ignore-regex": "http-equiv"
```
