### ISSUE TITLE
Why it doesn't recognize BEM?

### ISSUE THREAD

**Issue by serjyamp** [htmllint/htmllint#189]
I have this in my .html
`<div class="container__el__el"></div>`
It is incorrect naming in BEM (element can not have element).
Why don't linter show me any error?

**Comment by mlochbaum** [comment]
Because BEM is hard to verify using regex? I would accept a pull request for a rule that checks BEM class names, and there's a very small chance that I will feel motivated to read up on it myself.

**Comment by yvanavermaet** [comment]
I'm working on this one. Will keep you posted.

**Comment by yvanavermaet** [comment]
Pull request available @mlochbaum
