### ISSUE TITLE
tag-self-close options not working

### ISSUE THREAD

**Issue by jitendravyas** [htmllint/htmllint#191]
https://github.com/htmllint/htmllint/wiki/Options#tag-self-close

Get same error in both cases 

> "always": Void elements must be self-closed with / (html4 style).
> "never": Void elements must not be self-closed with / (html5 style).

**Comment by mlochbaum** [comment]
There are tests; it's definitely working. The split into always and never has not made it into an npm release yet, so if you're using v0.6.0 they will both just be interpreted as true.
