### ISSUE TITLE
Linter fails because some rules only expect specific format as input

### ISSUE THREAD

**Issue by devconcept** [htmllint/htmllint#196]
The [Issue](https://github.com/htmllint/htmllint/blob/master/lib/issue.js#L1) constructor expect some arguments in order like code, position and additional data. Some rules expect some specific format for the input and this causes sometimes the Linter to fail with the error

    Cannot read property 0 of undefined

Here is an example:

For the input "foobar" which is obviously wrong html input, the Linter parse it as one text node. 

If you apply the [`doctype-first`](https://github.com/htmllint/htmllint/blob/master/lib/rules/doctype-first.js) rule, it will detect the error and [create](https://github.com/htmllint/htmllint/blob/master/lib/rules/doctype-first.js#L44) a new `E007` issue but the text node does not have an `openLineCol` property because is not an element. This causes `undefined` to be passed as the `pos` argument causing the failure later at the issue constructor.

    function Issue(code, pos, data) {
        // Here pos is undefined
        this.line = pos[0];
        this.column = pos[1];
        this.code = code;
        this.data = data || {};
    }

**Comment by mlochbaum** [comment]
Similar problem to #205. I'm starting to think that using openLineCol for tags and lineCol for other elements is a bad idea...
