### ISSUE TITLE
attr-name-style rule causing false positive

### ISSUE THREAD

**Issue by branpar** [htmllint/htmllint#204]
Hello,

When using the default for `attr-name-style` (lowercase) I am receiving errors on elements which have data- attributes on them, stating they are not lowercase.  HTML5 data- attributes should not consider the '-' as an uppercase letter because it's not in the [a-z] character range.

To validate if I take the '-' out of the markup and run this again it does not show the error.

**Comment by nwoltman** [comment]
You can set `attr-name-style` to `"dash"` to fix this (`dash` should be the default, but unfortunately the default is `lowercase`).

**Comment by mlochbaum** [comment]
Yes, that's a better default. It'll be included in 1.0.0.
