### ISSUE TITLE
spec-char-escape gives invalid line/col numbers

### ISSUE THREAD

**Issue by branpar** [htmllint/htmllint#205]
Hi,

When using the defaults for `spec-char-escape` rule I am getting the error but the line and column numbers are incorrect. As an example I have this error (&) in my file, on line 75, column 182, but the reporter is giving me:

`line 1  col 8   text contains improperly escaped characters: &  (E023)`

However if I escape this character only and re-run the error goes away.

**Comment by mlochbaum** [comment]
Line/column numbers are another thing that should be tested...
