### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by croso-df** [htmllint/htmllint#212]
Do you have any plans on releasing an IDE extension on top of htmllint? I'm up to the challenge of doing so for vscode, but I better double check if some work is being developed already.

**Comment by mlochbaum** [comment]
I'm not aware of anyone doing that. Go for it!

**Comment by coliff** [comment]
Hey @croso-df - did you make any progress on this? I'd love to see a VSCode extension for this...

**Comment by jcklpe** [comment]
I'd also love to hear more!

**Comment by KamiKillertO** [comment]
I've just published the exension 🎉 https://marketplace.visualstudio.com/items?itemName=kamikillerto.htmllint

**Comment by mlochbaum** [comment]
I'll consider this resolved then. Thank you, and feel free to raise more issues if there is anything that would be helpful on the linter side.
