### ISSUE TITLE
Error: Index passed to line/column function (2) does not keep with order (last was 16)

### ISSUE THREAD

**Issue by Lucas-C** [htmllint/htmllint#216]
With `htmllint-cli@0.0.6`, there is a minimal bug reproduction example:
```
<!DOCTYPE html>
<html lang="en">
<body>
<script type="text/javascript">
'&' + [].join('&');
</script>
</body>
</html>
```

The execution result:
```
$ htmllint index.html
[htmllint error in index.html ] Error: Index passed to line/column function (2) does not keep with order (last was 16)
[htmllint] found 0 errors out of 1 files
```

This was already reported in #192, but without any example provided

**Comment by mlochbaum** [comment]
The crash is fixed in version 0.7.0. I intend to update htmllint-cli (and hopefully address some of the issues for that project) soon, but I won't have time to do so in the next two weeks.
