### ISSUE TITLE
Disable all default rules

### ISSUE THREAD

**Issue by jonashaag** [htmllint/htmllint#219]
Maybe I'm just blind but I'd like to achieve the following: Have htmllint only use the explicit list of rules I give it.

I tried to specify the `validate` preset in .htmllintrc somehow, but I couldn't figure out if this is even possible. (From looking at the source code, it doesn't seem to.)

**Comment by mlochbaum** [comment]
The preset `none` is defined sneakily in `lib/presets/index.js`. I guess the wiki page on inline configuration is due for an update.

If an htmllint-based tool doesn't let you use a preset, please file an issue there. I plan on looking at the cli and grunt packages next week.
