### ISSUE TITLE
SVG is case sensitive

### ISSUE THREAD

**Issue by croso-df** [htmllint/htmllint#228]
Given that SVG tags are case sensitive for browser parsers, the linter shouldn't complain when detecting camelCase tags inside <svg>. 

Take for example `<feGaussianBlur stdDeviation="5"></feGaussianBlur>`, if I change this to `<fegaussianblur stdDeviation="5"></fegaussianblur>`, the blur filter won't work at all.

**Comment by mlochbaum** [comment]
Duplicate of #137, which is one of the top priorities for the next version of htmllint.
