### ISSUE TITLE
Output verbose errors

### ISSUE THREAD

**Issue by OSP123** [htmllint/htmllint#231]
Currently working under Nick Bartlett on an automated grading application for work. Part of the application requires linting and displays the error back to the user. The API for htmllint has been amazing and so much easier to use than the Nu validator! However, I don't think students will be able to understand the error outputs in its current format. Is there a way to display the errors verbosely? 

Here is the output I'm seeing so far:
<img width="855" alt="screen shot 2018-02-14 at 4 19 25 pm" src="https://user-images.githubusercontent.com/1403723/36234991-e9be297c-11a2-11e8-8f20-15f2b0cbe322.png">

Thanks!

**Comment by mlochbaum** [comment]
If you're calling htmllint directly, then `htmllint.messages.renderIssue(issue)` will return a text description for an issue. See https://github.com/htmllint/htmllint-cli/blob/master/bin/cli.js#L116 for an example.

**Comment by OSP123** [comment]
Oh, nice, I'll check that out! Does it work via the Node API or only the CLI?

**Comment by mlochbaum** [comment]
It's a Javascript function, so it has to be called from node. The CLI uses it to format output.

**Comment by OSP123** [comment]
Okay, I'm going to try it out. Thanks!

**Comment by OSP123** [comment]
Works, thank you :)
