### ISSUE TITLE
Setting class-style to "none" gives error

### ISSUE THREAD

**Issue by krike** [htmllint/htmllint#241]
For `class-style` in the wiki it says:
```A format specifier, "none", or false. If set, classes must fit the given format. If false, the value for id-class-style is used instead (use 'none' to avoid matching anything).```

When I use `"class-style": "none"` I get `Fatal error: Cannot read property 'test' of undefined` in the grunt-html-linter and even `"class-style": "/^[a-zA-Z0-9-_]+$/g",` gives the same error. (I'm not sure `class-style` accepts regex string but `id-class-style` gives the same error)

When I'm setting both id and class to false I get (`id-class-style`): 
`Running "htmllint:src" (htmllint) task
Fatal error: Cannot get options for index 382 when index 382 has already been checked`

Am I using it wrong? ps: I'm using the latest version (0.7.2) and grunt-htmllint (0.2.7)

**Comment by mlochbaum** [comment]
grunt-htmllint was using htmllint version 0.2.4, which is just a little out of date. Try with grunt-htmllint version 0.3.0.
