### ISSUE TITLE
Is this package still active ?

### ISSUE THREAD

**Issue by KamiKillertO** [htmllint/htmllint#252]
This project is quite popular (10000 downloads/weeks)
But it seems that there haven't been any development on this project for the last seven month.
There's some opened PR that need to be merge and new rules that need to be released.
The same goes for the other projects [htmllint-cli](https://github.com/htmllint/htmllint-cli)/[htmllint.github.io](https://github.com/htmllint/htmllint.github.io)

If you need help for developing/maintaining this project I would like to help.
(@romnempire and @mlochbaum)

**Comment by KamiKillertO** [comment]
@mlochbaum? ☝️

**Comment by mlochbaum** [comment]
It's still active, and I have no plans to abandon it. My schedule will continue to be pretty intermittent, though. In this case I was kind of trying to decide whether to do anything in response to Microsoft's Github acquisition. My conclusion is that Github will probably start to decline in quality in about three years or so, but there aren't any alternatives that are safe from issues like this, so I'm stuck here.

The total amount of work to maintain the project is pretty low, so I'm not sure it's really worth the effort to start adding contributors. Pull requests for specific issues are always welcome.
