### ISSUE TITLE
feature_request(ignore): disable lint inside script and style tags

### ISSUE THREAD

**Issue by Kristinita** [htmllint/htmllint#257]
**#221** — related issue.

### 1. Summary

It would be nice, if htmllint will not lint JavaScript and CSS inside `<script>` and `<style>` tags.

### 2. Argumentation

I use [**critical**](https://github.com/addyosmani/critical/) to improve my site performance, that [**officially recommended by Google**](https://developers.google.com/web/tools/lighthouse/audits/unused-css). It requires [**loadCSS**](https://github.com/filamentgroup/loadCSS/) script inside `<script>` tag and critical CSS inside `<style>`.

#### 3.1. Files

+ `Kira_htmllint__critical_CSS--non-expected_behavior.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kira htmllint script demo</title>
    <link href="https://cdn.jsdelivr.net/npm/gemini-scrollbar/gemini-scrollbar.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <style>.KiraExampleTag>div{color:#fff}</style>
    <script>!function(n){"use strict";n.loadCSS||(n.loadCSS=function(){});var o=loadCSS.relpreload={};if(o.support=function(){var e;try{e=n.document.createElement("link").relList.supports("preload")}catch(t){e=!1}return function(){return e}}(),o.bindMediaToggle=function(t){var e=t.media||"all";function a(){t.addEventListener?t.removeEventListener("load",a):t.attachEvent&&t.detachEvent("onload",a),t.setAttribute("onload",null),t.media=e}t.addEventListener?t.addEventListener("load",a):t.attachEvent&&t.attachEvent("onload",a),setTimeout(function(){t.rel="stylesheet",t.media="only x"}),setTimeout(a,3e3)},o.poly=function(){if(!o.support())for(var t=n.document.getElementsByTagName("link"),e=0;e<t.length;e++){var a=t[e];"preload"!==a.rel||"style"!==a.getAttribute("as")||a.getAttribute("data-loadcss")||(a.setAttribute("data-loadcss",!0),o.bindMediaToggle(a))}},!o.support()){o.poly();var t=n.setInterval(o.poly,500);n.addEventListener?n.addEventListener("load",function(){o.poly(),n.clearInterval(t)}):n.attachEvent&&n.attachEvent("onload",function(){o.poly(),n.clearInterval(t)})}"undefined"!=typeof exports?exports.loadCSS=loadCSS:n.loadCSS=loadCSS}("undefined"!=typeof global?global:this);</script>
</head>
<body>
    <div>Kira Goddess!</div>
</body>
</html>

```

+ `.htmllintrc`:

```json
{
    "indent-style": "tabs",
    "tag-bans": ["b", "i"]
}

```

#### 4.1. Expected

No errors.

#### 4.2. Actual

```js
D:\Kristinita>htmllint "Kira_htmllint__critical_CSS--non-expected_behavior.html"
Kira_htmllint__critical_CSS--non-expected_behavior.html: line 8, col 25, text contains an unescaped angle bracket: >
Kira_htmllint__critical_CSS--non-expected_behavior.html: line 9, col 371, text contains an ill-formed escape sequence: &&
Kira_htmllint__critical_CSS--non-expected_behavior.html: line 9, col 500, text contains an ill-formed escape sequence: &&
Kira_htmllint__critical_CSS--non-expected_behavior.html: line 9, col 696, text contains an unescaped angle bracket: <
Kira_htmllint__critical_CSS--non-expected_behavior.html: line 9, col 1018, text contains an ill-formed escape sequence: &&

[htmllint] found 5 errors out of 1 files

```

### 5. Do not offer

1. Please do not say that I shouldn't use `<style>` and `<script>` tags. Please, read `Argumentation` section.

2. Yes, this regex works for me.

    ```json
    {
        "raw-ignore-regex": "/(\\<script\\>.*\\<\/script\\>|\\<style\\>.*\\<\/style\\>)/"
    }
    ```

    But it would be nice, if ignoring `<style>` and `<script>` tag will be possible by default. htmllint — not a tool for checking CSS and JavaScript.

Thanks.

**Comment by mlochbaum** [comment]
This is a much easier fix than I realized when I commented on #221. There's actually no reason to traverse `script` or `style` tags in any current rules, so I have just added some code to dom.js to skip them. I'm kicking myself for not having figured that out a year ago.

I definitely agree that htmllint should work even if you use `script` or `style` tags. It should support any sane way of writing html (and some insane ones). In fact I'm not really sure `style` should be a banned tag by default. I may remove it the next time I bump the minor version.
