### ISSUE TITLE
use bulk-require instead of require-all

### ISSUE THREAD

**Issue by coalman** [htmllint/htmllint#41]
In order to compile this stuff with browserify, we probalby need to use substack's [bulk-require](https://www.npmjs.org/package/bulk-require) instead of require-all.
- [x] remove all uses of require-all and replace with bulk-require (use `bulk` for the import name)
- [x] remove require-all from package.json so that it isn't a dependency anymore

**Comment by nbriz** [comment]
hi there! was this ever fixed? i'm trying to "browserify" a project in which i'm hoping to use htmllint, but if i try to `require('htmllint')` in my project i get this error when i try to browserify it:
`Error: Cannot find module 'bulkify' from 'path/to/my/project/node_modules/htmllint'`
