### ISSUE TITLE
tag-name-match prevents other lint errors from being reported

### ISSUE THREAD

**Issue by Coalman** [htmllint/htmllint#97]
Did a bit of testing after being alerted by @yvanavermaet. This seems to happen in the grunt and gulp plugins.

**Comment by yvanavermaet** [comment]
I've noticed that the tag-name-match would also report the self-closing tags as error.

**Comment by mlochbaum** [comment]
I've changed tag-name-match to prevent it from throwing on self-closing elements, which should fix the problem. I have not confirmed that it prevents the reported error when run with grunt.
